name: ApiManager
version: '4.1.1'
main: de.lars.apimanager.Main
api-version: '1.21'
author: KompetenzL0s
description: A Plugin by Lars as MySQL Api for UtilsManager

UtilsManager:
  load: AFTER
  required: false