name: ApiManager
version: '4.2.1'
main: de.lars.apimanager.ApiManager
api-version: '1.21'
author: KompetenzL0s
description: A Plugin by Lars as MySQL Api for UtilsManager

UtilsManager:
  load: AFTER
  required: false